name: deployment Test

on:
  push:
    branches:
      - 'test_branch'

jobs:
  test:
    name: Test - Unit & Integration
    runs-on: ubuntu-18.04
    
    strategy:
      matrix:
        node-version: [14.6.0]
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 14.6.0
        uses: actions/setup-node@v1
        with: 
          node-version: 14.6.0
      - name: Config dependencies
        run: npm config set unsafe-perm true
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm test -- --coverage
      - name: Build
        run: npm run build
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-18.04
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build Docker image
        run: docker build -t $REPO:latest  .
      - name: Publish Docker image
        run: docker push $REPO

  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-18.04
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: https://webhook.nxncloud.io/hooks/deploymentTest